# Ambiente MySQL
# Prof. Taciano Balardin
version: "1.0"
services:
    db:
        image: mysql:8.0
        container_name: 'mysql'
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 1q2w3e4r5t 
        volumes:
          - ./database/mysql:/var/lib/mysql
          - ./database/logs:/var/log/mysql
          - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - default
networks:
    default:
        driver: bridge
